import Cart from './Cart';
import increaseValueInMap, { calculateImages } from './tools/Functions';
import { FilterCalculator } from './FilterCalculator';
import { PAGES_HASH } from './constants/constants';
import {
    ProductDetails,
    DummyJSON,
    ShownProductInfo,
    filterParamsKeys,
    FilterKeys,
    FilterParamsValues,
    FilteredProductsKeys,
    InitialFilterValues,
    ModelData,
    SortVariantsEnum,
    PageCase,
} from './intefaces/types';

class Model {
    queryParams: URLSearchParams;
    cart: Cart | null;
    productJSON: DummyJSON | null;
    modelData: ModelData;
    filterCalculator: FilterCalculator;
    shownProductInfo: ShownProductInfo | null;

    constructor(urlString: string = window.location.href) {
        const url = new URL(urlString);
        this.queryParams = url.searchParams;
        this.cart = null;
        this.filterCalculator = new FilterCalculator();
        this.productJSON = null;
        this.modelData = {
            activeFilters: {},
            initialFilterValues: {
                minPrice: Infinity,
                maxPrice: 0,
                minStock: Infinity,
                maxStock: 0,
                categories: new Map(),
                brands: new Map(),
            },
            allBrands: [],
            allCategories: [],
            initialProducts: null,
            filteredProducts: null,
            currentOption: null,
            shownProductInfo: null,
            calculatedFilters: null,
            page: this.getPageFromURL(),
            detailsID: Number(this.getDetailsID()),
            detailsMainImageSrc: '',
            cart: null,
        };
        this.shownProductInfo = null;
    }
    async loadProducts(source = 'https://dummyjson.com/products?limit=100'): Promise<void> {
        try {
            const response = await fetch(source);
            const data = await response.json();
            this.productJSON = data;
            if (this.productJSON?.products) {
                this.productJSON.products = this.productJSON.products.slice(0, 50);
                this.productJSON.products.forEach((elem: ProductDetails) => {
                    elem.isImagesUnique = false;
                });
            }
            this.cart = new Cart(this.productJSON && this.productJSON.products);
            this.readParamsFromURL();
            this.findInitialFilterValues();
            this.applyQueryParamsToFilter();
            this.applyQueryParam();
            this.modelData.cart = this.cart;
        } catch {
            throw new Error('Fail to connect dummy json');
        }
    }
    getPageFromURL(): PageCase {
        const currentHash = window.location.hash;
        const detailLength = PAGES_HASH.details.length;

        if (currentHash === PAGES_HASH.store || currentHash === '') {
            return PageCase.store;
        }
        if (currentHash === PAGES_HASH.cart) {
            return PageCase.cart;
        }
        if (currentHash.slice(0, detailLength) === PAGES_HASH.details) {
            return PageCase.details;
        }
        return PageCase.error;
    }
    getDetailsID(): string {
        const detailLength = PAGES_HASH.details.length;
        return window.location.hash.slice(detailLength);
    }
    isPage(url = window.location): true {
        console.log('check url to be url generated by the app', url);
        return true;
    }
    updatePage() {
        this.modelData.page = this.getPageFromURL();
        if (this.modelData.page === PageCase.details) {
            this.modelData.detailsID = Number(this.getDetailsID());
        }
        this.readParamsFromURL();
        this.findInitialFilterValues();
        this.applyQueryParam();
    }
    readParamsFromURL(): Partial<FilterParamsValues> {
        const activeFilters: Partial<FilterParamsValues> = {};
        this.queryParams = new URL(window.location.href).searchParams;

        for (const key of this.queryParams.keys()) {
            if (filterParamsKeys.includes(key as FilterKeys)) {
                const filter = key;
                activeFilters[filter as keyof typeof activeFilters] = this.queryParams.getAll(key);
            } else {
                console.log(`${key} is not a key!`);
            }
        }
        this.modelData.activeFilters = activeFilters;
        return activeFilters;
    }
    applyQueryParamsToFilter(): void {
        const active = this.modelData.activeFilters;
        this.filterCalculator = new FilterCalculator();
        active.brand?.map((brand) => {
            this.filterCalculator.addBrand(brand);
        });
        active.category?.map((category) => {
            this.filterCalculator.addCategory(category);
        });
        if (active.priceMax) {
            this.filterCalculator.updateMaxUserPrice(+active.priceMax[0]);
        }
        if (active.priceMin) {
            this.filterCalculator.updateMinUserPrice(+active.priceMin[0]);
        }
        if (active.stockMax) {
            this.filterCalculator.updateMaxUserStock(+active.stockMax[0]);
        }
        if (active.stockMin) {
            this.filterCalculator.updateMinUserStock(+active.stockMin[0]);
        }
        if (active.searching) {
            this.filterCalculator.updateSearchName(active.searching[0]);
        }
        this.modelData.calculatedFilters = this.filterCalculator;
        this.shownProductInfo = this.filterCalculator.recalculate(
            this.productJSON?.products || null,
            history.state?.key
        );
        //console.log('PRODUCT INFO', this.shownProductInfo);
        //console.log('FILTER input INFO', this.filterCalculator);
    }
    applyQueryParamsToCart() {
        const active = this.modelData.activeFilters;
        if (!this.cart) {
            throw new Error('Cart is not initialized');
        }
        if (active.cartListLimit) {
            this.cart.limit = +active.cartListLimit[0];
        }
        if (active.cartListPage) {
            const pageFromQuery: number = +active.cartListPage[0];
            const lastPage: number = this.cart.lastPage();
            if (lastPage < pageFromQuery) {
                this.changeParamInURL('cartListPage', `${lastPage}`);
                this.reInit();
            } else {
                this.cart.listPage = +active.cartListPage[0];
            }
        }
    }
    applyQueryParamsToSorting() {
        this.sortProducts(this.modelData.activeFilters.sorting?.[0] as SortVariantsEnum);
    }
    findInitialFilterValues() {
        if (this.productJSON && this.productJSON.products) {
            const allProducts: Array<ProductDetails> = this.productJSON.products;
            const allCategories: Array<string> = [];
            const allBrands: Array<string> = [];

            const productsSummaryInfo: InitialFilterValues = allProducts.reduce(
                (info: InitialFilterValues, product: ProductDetails) => {
                    info.minPrice = Math.min(info.minPrice, product.price);
                    info.maxPrice = Math.max(info.maxPrice, product.price);

                    info.minStock = Math.min(info.minStock, product.stock);
                    info.maxStock = Math.max(info.maxStock, product.stock);

                    allCategories.push(product.category);
                    allBrands.push(product.brand);

                    increaseValueInMap(info.categories, product.category);
                    increaseValueInMap(info.brands, product.brand);

                    return info;
                },
                {
                    minPrice: Infinity,
                    maxPrice: 0,
                    minStock: Infinity,
                    maxStock: 0,
                    categories: new Map(),
                    brands: new Map(),
                }
            );
            this.modelData.allBrands = [...new Set(allBrands)];
            this.modelData.allCategories = [...new Set(allCategories)];
            this.modelData.initialProducts = this.productJSON.products;
            this.modelData.initialFilterValues = productsSummaryInfo;
            return productsSummaryInfo;
        }
    }
    createQueryParamFromEvent(key: FilterKeys, value: string, secondValue?: number) {
        switch (key) {
            case 'sorting': {
                this.changeParamInURL('sorting', value);
                this.reInit();
                break;
            }
            case 'category': {
                if (this.filterCalculator.categories.has(value)) {
                    this.deleteParamFromURL('category', value);
                } else {
                    this.appendParamToURL('category', value);
                }
                this.reInit();
                break;
            }
            case 'brand': {
                if (this.filterCalculator.brands.has(value)) {
                    this.deleteParamFromURL('brand', value);
                } else {
                    this.appendParamToURL('brand', value);
                }
                this.reInit();
                break;
            }
            case 'priceMin': {
                if (secondValue && +value > secondValue) {
                    this.changeParamInURL('priceMax', value);
                    this.changeParamInURL('priceMin', `${secondValue}`);
                } else {
                    this.changeParamInURL('priceMin', value);
                }
                this.reInit();
                break;
            }
            case 'priceMax': {
                if (secondValue && +value < secondValue) {
                    this.changeParamInURL('priceMin', value);
                    this.changeParamInURL('priceMax', `${secondValue}`);
                } else {
                    this.changeParamInURL('priceMax', value);
                }
                this.reInit();
                break;
            }
            case 'stockMin': {
                if (secondValue && +value > secondValue) {
                    this.changeParamInURL('stockMax', value);
                    this.changeParamInURL('stockMin', `${secondValue}`);
                } else {
                    this.changeParamInURL('stockMin', value);
                }
                this.reInit();
                break;
            }
            case 'stockMax': {
                if (secondValue && +value < secondValue) {
                    this.changeParamInURL('stockMin', value);
                    this.changeParamInURL('stockMax', `${secondValue}`);
                } else {
                    this.changeParamInURL('stockMax', value);
                }
                this.reInit();
                break;
            }
            case 'searching': {
                this.changeParamInURL('searching', value);
                this.reInit();
                break;
            }
            case 'cartListLimit': {
                if (this.cart) {
                    const integer = +value < 1 ? 1 : Math.floor(+value);
                    const newLimit = Math.min(integer, this.cart.products.size);
                    this.changeParamInURL('cartListLimit', `${newLimit}`);
                }
                this.reInit();
                break;
            }
            case 'cartListPage': {
                if (this.cart && this.cart.checkValidPage(+value)) {
                    this.changeParamInURL('cartListPage', value);
                    this.reInit();
                }
                break;
            }
        }
    }
    applyQueryParam() {
        //console.log('apply filters to product list');
        this.modelData.shownProductInfo = this.shownProductInfo;
        this.modelData.filteredProducts = this.shownProductInfo?.shownProducts || null;
        this.modelData.detailsMainImageSrc = this.modelData.filteredProducts?.find(
            (elem) => elem.id === this.modelData.detailsID
        )?.images[0];
        console.log();
        this.applyQueryParamsToSorting();
        this.applyQueryParamsToCart();
    }
    getAscendingSorting(filteredProductsInModelData: ProductDetails[], sortProperty: FilteredProductsKeys): void {
        filteredProductsInModelData.sort((prev, curr) => {
            return +prev[sortProperty] - +curr[sortProperty];
        });
    }
    getDescendingSorting(filteredProductsInModelData: ProductDetails[], sortProperty: FilteredProductsKeys): void {
        filteredProductsInModelData.sort((prev, curr) => {
            return +curr[sortProperty] - +prev[sortProperty];
        });
    }
    sortProducts(sortVariant: SortVariantsEnum): void {
        if (this.modelData.filteredProducts) {
            this.modelData.currentOption = sortVariant;
            switch (sortVariant) {
                case SortVariantsEnum.DEFAULT:
                    {
                        this.getAscendingSorting(this.modelData.filteredProducts, 'id');
                    }
                    break;
                case SortVariantsEnum.PRICE_ASCENDING:
                    {
                        this.getAscendingSorting(this.modelData.filteredProducts, 'price');
                    }
                    break;
                case SortVariantsEnum.PRICE_DESCENDING:
                    {
                        this.getDescendingSorting(this.modelData.filteredProducts, 'price');
                    }
                    break;
                case SortVariantsEnum.RATING_ASCENDING:
                    {
                        this.getAscendingSorting(this.modelData.filteredProducts, 'rating');
                    }
                    break;
                case SortVariantsEnum.RATING_DESCENDING:
                    {
                        this.getDescendingSorting(this.modelData.filteredProducts, 'rating');
                    }
                    break;
                default:
                    {
                        this.getAscendingSorting(this.modelData.filteredProducts, 'id');
                    }
                    break;
            }
        }
    }
    appendParamToURL(key: FilterKeys, value: string) {
        const url: URL = new URL(window.location.href);
        const urlSearch: URLSearchParams = url.searchParams;
        urlSearch.append(key, value);
        url.search = urlSearch.toString();

        history.pushState({ key, value }, '', url.toString());
        //console.log('add category to url search params');
    }
    deleteParamFromURL(key: FilterKeys, param: string) {
        const url: URL = new URL(window.location.href);
        const urlSearch: URLSearchParams = url.searchParams;
        const values = urlSearch.getAll(key).filter((value) => value !== param);
        urlSearch.delete(key);
        values.forEach((value) => {
            urlSearch.append(key, value);
        });
        url.search = urlSearch.toString();

        history.pushState({ key, values }, '', url.toString());
        //console.log('delete category from url search params');
    }
    changeParamInURL(key: FilterKeys, value: string) {
        const url: URL = new URL(window.location.href);
        const urlSearch: URLSearchParams = url.searchParams;
        urlSearch.set(key, value);
        url.search = urlSearch.toString();

        history.pushState({ key, value }, '', url.toString());
    }
    reInit() {
        this.readParamsFromURL();
        this.applyQueryParamsToFilter();
        this.applyQueryParamsToSorting();
        this.applyQueryParam();
    }
}

export default Model;
